# Generated by Django 2.1.7 on 2019-02-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='images',
            name='source_page',
            field=models.CharField(max_length=400),
        ),
    ]
