# Generated by Django 2.1.7 on 2019-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageface', '0002_auto_20190214_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='link',
            field=models.CharField(max_length=400),
        ),
    ]
