# Generated by Django 2.1.7 on 2019-02-17 11:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageface', '0003_auto_20190214_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='contents',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
