# Generated by Django 2.1.7 on 2019-02-14 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imageface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='source',
            new_name='source_page',
        ),
        migrations.AddField(
            model_name='images',
            name='source_page_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='source_site_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
