# Generated by Django 2.1.7 on 2019-02-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageface', '0002_auto_20190214_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='images',
            name='source_page_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='images',
            name='source_site_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
