# Generated by Django 2.1.7 on 2019-02-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageface', '0003_auto_20190214_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='source_page_title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='source_site_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
